

INSERT INTO city
(ID,NAME)
VALUES
(1,'BANGLORE');

INSERT INTO referee
(ID,NAME)
VALUES
(2,'SAI');

INSERT INTO extra_type
(ID,NAME)
VALUES
(3,'CHAITANYA');


-INSERT INTO skill
(ID,NAME)
VALUES
(4,'NAGA');

-INSERT INTO team
(ID,NAME,COACH,HOME_CITY,CAPTAIN)
VALUES
(2,'CHAITANYA','ANANTAPUR','DHONI');

INSERT INTO player
(ID,NAME,COUNTRY,SKILL_ID,TEAM_ID)
VALUES
(2,'SAI','INDIA',5,7);

INSERT INTO  venue
(ID,STADIUM_NAME,CITY_ID)
VALUES
(2,'CHINNASWAMY',4);

INSERT INTO  event
(ID,INNINGS_ID,EVENT_NO,RAIDER_ID,RAID_POINTS,DEFENDING_POINTS,CLOCK_IN_SECONDS,TEAM_ONE_SCORE,TEAM_TWO_SCORE)
VALUES
(2,1,4,5,10,20,50,25,27);

INSERT INTO  game
(ID,GAME_DATE,TEAM_ID_2,TEAM_ID_1VENUE_ID,OUTCOME_ID,REFEREE_ID_1,REFEREE_ID_2,FIRST_INNINGS_ID,SECOND_INNINGS_ID)
VALUES
(2,15-07-2020,2,5,7,6,9,4,3);

--
UPDATE TABLE player
SET COUNTRY = 'USA'
WHERE NAME='sai';

UPDATE TABLE player
SET COUNTRY = 'USA'
WHERE NAME='sai';

UPDATE TABLE player
SET SKILL_ID = 10
WHERE TEAM_ID=7;

DELETE FROM extra_type WHERE ID=3;

DELETE FROM referee WHERE NAME='SAI;

DELETE FROM player WHERE TEAM_ID=7;






--13. Update player table

--14. Update player table

--15. Update player table

--16. Update player table

--17. Delete from extra_type

--18. Delete from referee

--19. Delete from player

--20. Delete from outcome
